# Generated by Django 4.2.23 on 2026-01-29 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
