# Generated by Django 4.2.23 on 2026-01-29 11:32

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('banking', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('revenue', 'Revenue'), ('expense', 'Expense')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_categories', to='core.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='finance.transactioncategory')),
            ],
            options={
                'verbose_name_plural': 'Transaction Categories',
                'ordering': ['category_type', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(help_text='Unique reference number (e.g. TRX-0001)', max_length=50, unique=True)),
                ('transaction_date', models.DateField(db_index=True, help_text='Date transaction occurred or is expected')),
                ('transaction_type', models.CharField(choices=[('invoice', 'Customer Invoice'), ('payment_received', 'Payment Received'), ('purchase', 'Supplier Purchase'), ('payment_made', 'Payment Made'), ('expense', 'Expense'), ('adjustment', 'Adjustment'), ('transfer', 'Internal Transfer')], db_index=True, max_length=20)),
                ('direction', models.CharField(choices=[('in', 'Money In'), ('out', 'Money Out')], db_index=True, max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Base amount before tax', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount including tax', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('party_type', models.CharField(blank=True, choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('internal', 'Internal'), ('other', 'Other')], max_length=20, null=True)),
                ('party_id', models.PositiveIntegerField(blank=True, null=True)),
                ('party_name', models.CharField(blank=True, help_text='Snapshot of customer/supplier name', max_length=255)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('check', 'Check'), ('card', 'Card'), ('other', 'Other')], max_length=20, null=True)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions', to='banking.bankaccount')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.transactioncategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('reference_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('related_transaction', models.ForeignKey(blank=True, help_text='Link payment to invoice, or refund to payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_modifications', to='finance.transaction')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['company', 'transaction_date'], name='finance_tra_company_dbc58b_idx'), models.Index(fields=['company', 'transaction_type', 'status'], name='finance_tra_company_ff87a7_idx'), models.Index(fields=['company', 'party_type', 'party_id'], name='finance_tra_company_aa6ec9_idx'), models.Index(fields=['company', 'direction', 'status'], name='finance_tra_company_36b7ea_idx'), models.Index(fields=['company', 'category', 'transaction_date'], name='finance_tra_company_199387_idx'), models.Index(fields=['reference_type', 'reference_id'], name='finance_tra_referen_2e0759_idx')],
            },
        ),
    ]
