# Generated by Django 4.2.23 on 2026-02-03 08:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0003_alter_bankaccount_account_number'),
        ('invoices', '0001_initial'),
        ('core', '0001_initial'),
        ('customers', '0002_alter_customer_unique_together_remove_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('payment_number', models.CharField(help_text='Unique payment reference number', max_length=50, unique=True)),
                ('payment_date', models.DateField(help_text='Date when payment was received')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total payment amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='External reference (cheque number, transaction ID, etc.)', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(blank=True, help_text='Bank account if payment method is bank/cheque', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='banking.bankaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.company')),
                ('customer', models.ForeignKey(help_text='Customer who made this payment', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.customer')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of payment allocated to this invoice', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='invoices.invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='payments.payment')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['payment', 'invoice'], name='payments_pa_payment_c36697_idx'), models.Index(fields=['invoice'], name='payments_pa_invoice_16fb19_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'invoice'), name='unique_payment_invoice_allocation'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', 'customer', 'payment_date'], name='payments_pa_company_51a62e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_number'], name='payments_pa_payment_a0847d_idx'),
        ),
    ]
