# Generated by Django 4.2.23 on 2026-01-29 09:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier')], help_text='Whether this entry is for a customer or supplier', max_length=20)),
                ('party_id', models.PositiveIntegerField(help_text='ID of the customer or supplier')),
                ('entry_type', models.CharField(choices=[('invoice', 'Invoice'), ('payment', 'Payment'), ('purchase', 'Purchase'), ('adjustment', 'Adjustment')], help_text='Type of transaction', max_length=20)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount owed TO us (increases balance)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount we owe OR received (decreases balance)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('running_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance after this entry (denormalized for performance)', max_digits=15)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of this entry')),
                ('transaction_date', models.DateField(help_text='Date of the transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='core.company')),
                ('reference_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'Ledger Entries',
                'ordering': ['transaction_date', 'created_at'],
                'indexes': [models.Index(fields=['company', 'party_type', 'party_id', 'transaction_date'], name='ledger_party_date_idx'), models.Index(fields=['company', 'party_type', 'entry_type'], name='ledger_type_idx'), models.Index(fields=['reference_type', 'reference_id'], name='ledger_reference_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_type__isnull', False)), fields=('reference_type', 'reference_id', 'entry_type'), name='unique_reference_entry'),
        ),
    ]
