# Generated by Django 4.2.23 on 2026-02-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
